"""create fresh paper_review table

Revision ID: 05c3975bc951
Revises: 
Create Date: 2025-08-16 18:39:03.015148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05c3975bc951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_review',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aixiv_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=45), nullable=False),
    sa.Column('review_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_type', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('doc_type', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('like_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_review_aixiv_id_create_time', 'paper_review', ['aixiv_id', 'create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_paper_review_aixiv_id_create_time', table_name='paper_review')
    op.drop_table('paper_review')
    # ### end Alembic commands ### 