"""add userid and ip to paper_review

Revision ID: b8949439e623
Revises: abc123456789
Create Date: 2025-08-20 16:57:40.605076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8949439e623'
down_revision: Union[str, None] = 'abc123456789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_review', sa.Column('userid', sa.String(length=128), nullable=True))
    op.add_column('paper_review', sa.Column('ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_review', 'ip')
    op.drop_column('paper_review', 'userid')
    # ### end Alembic commands ###
